services:
  stars-api:
    build:
      context: ../
      dockerfile: .docker/Dockerfile
    container_name: stars-api
    environment:
      PORT: 8000
      DEBUG: 1
    ports:
      - '8000:80'
    volumes:
      - ../app:/code/app
    restart: "no"
    command: uvicorn app.main:app --host 0.0.0.0 --port 80 --reload
